# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a48efd4140970e20572fb063eabb59ed3dcdd70c310a7ad18f3b7dfb64088c0f7bcf0fc76d6643d731aa2446402e99cf03bd1ae19a1643705305e7352ee786c

test:
  secret_key_base: f7bdc305982af48b38a17b274175499cc1ff360cced4ce4b97589e20bc6e0403a36976fd38fbe458646d46ada4f2a92edb839b43d92fa71f48cde249f293556e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
